// Code generated by protoc-gen-go. DO NOT EDIT.
// source: githubreceiver.proto

package githubreceiver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	TimeBetweenQueueProcess int64    `protobuf:"varint,1,opt,name=time_between_queue_process,json=timeBetweenQueueProcess,proto3" json:"time_between_queue_process,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7162ad0e80472c, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetTimeBetweenQueueProcess() int64 {
	if m != nil {
		return m.TimeBetweenQueueProcess
	}
	return 0
}

type Ping struct {
	Action               string      `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Issue                *Issue      `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	Ref                  string      `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Repository           *Repository `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7162ad0e80472c, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Ping) GetIssue() *Issue {
	if m != nil {
		return m.Issue
	}
	return nil
}

func (m *Ping) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *Ping) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type Repository struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7162ad0e80472c, []int{2}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Issue struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7162ad0e80472c, []int{3}
}

func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (m *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(m, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Issue) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "githubreceiver.Config")
	proto.RegisterType((*Ping)(nil), "githubreceiver.Ping")
	proto.RegisterType((*Repository)(nil), "githubreceiver.Repository")
	proto.RegisterType((*Issue)(nil), "githubreceiver.Issue")
}

func init() { proto.RegisterFile("githubreceiver.proto", fileDescriptor_cc7162ad0e80472c) }

var fileDescriptor_cc7162ad0e80472c = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0xf3, 0x83, 0xbd, 0x82, 0xc8, 0xa5, 0x6a, 0xa8, 0x9b, 0x92, 0x55, 0x41, 0xa8,
	0xa0, 0x3b, 0xc5, 0x8d, 0xe2, 0xa2, 0x1b, 0xa9, 0xf3, 0x02, 0x21, 0x09, 0x37, 0x71, 0x20, 0x99,
	0x89, 0xf3, 0xa3, 0xf8, 0x28, 0xbe, 0xad, 0xcc, 0x24, 0x55, 0x9b, 0xdd, 0x99, 0xfb, 0x9d, 0x73,
	0x38, 0x0c, 0x2c, 0x1a, 0x6e, 0xde, 0x6c, 0xa9, 0xa8, 0x22, 0xfe, 0x41, 0x6a, 0xd3, 0x2b, 0x69,
	0x24, 0x9e, 0x1c, 0x5e, 0xb3, 0x67, 0x48, 0x9e, 0xa4, 0xa8, 0x79, 0x83, 0xf7, 0xb0, 0x34, 0xbc,
	0xa3, 0xbc, 0x24, 0xf3, 0x49, 0x24, 0xf2, 0x77, 0x4b, 0x96, 0xf2, 0x5e, 0xc9, 0x8a, 0xb4, 0x4e,
	0x83, 0x55, 0xb0, 0x0e, 0xd9, 0x85, 0x73, 0x3c, 0x0e, 0x86, 0x57, 0xc7, 0x77, 0x03, 0xce, 0xbe,
	0x03, 0x88, 0x76, 0x5c, 0x34, 0x78, 0x0e, 0x49, 0x51, 0x19, 0x2e, 0x85, 0x4f, 0xcc, 0xd9, 0xf8,
	0xc2, 0x2b, 0x88, 0xb9, 0xd6, 0x96, 0xd2, 0xd9, 0x2a, 0x58, 0x1f, 0xdf, 0x9c, 0x6d, 0x26, 0xeb,
	0xb6, 0x0e, 0xb2, 0xc1, 0x83, 0xa7, 0x10, 0x2a, 0xaa, 0xd3, 0xd0, 0x37, 0x38, 0x89, 0x77, 0x00,
	0x8a, 0x7a, 0xa9, 0xb9, 0x91, 0xea, 0x2b, 0x8d, 0x7c, 0xc7, 0x72, 0xda, 0xc1, 0x7e, 0x1d, 0xec,
	0x9f, 0x3b, 0x7b, 0x00, 0xf8, 0x23, 0x88, 0x10, 0x89, 0xa2, 0xa3, 0x71, 0x9e, 0xd7, 0x78, 0x09,
	0xf3, 0xda, 0xb6, 0x6d, 0xee, 0xc1, 0xcc, 0x83, 0x23, 0x77, 0x78, 0x29, 0x3a, 0xca, 0xae, 0x21,
	0xde, 0xee, 0x57, 0x59, 0xd5, 0x8e, 0x41, 0x27, 0x71, 0x01, 0xb1, 0xe1, 0xa6, 0xdd, 0x67, 0x86,
	0x47, 0x99, 0xf8, 0x9f, 0xbe, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xe1, 0x7f, 0x33, 0x81,
	0x01, 0x00, 0x00,
}
